version: '3'

services:
  defichain:
    image: defi/defichain
    command: >
      defid
      -printtoconsole
      -regtest=1
      -rpcbind=0.0.0.0
    ports:
      - "19554:19554"
      - "19555:19555"
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
